[default]
db_host_name="localhost"
db_port_number="5432"
db_database_name="deposit"
db_user_name="dbuser"
db_pool_min_connection=1
db_pool_max_connection=15
monitoring_dns_lookup="dns.google.com"
monitoring_memory_limit=80
monitoring_cpu_limit=90
monitoring_db_pool_limit=10
debug_mode="False"

[dev]
db_host_name="localhost"
db_port_number="5432"
db_database_name="deposit"
db_user_name="dbuser"
debug_mode="True"


[prod]
db_host_name="database"
db_port_number="5432"
db_database_name="deposit"
db_user_name="dbuser"
debug_mode="False"


