version: '3.8'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 'dbpass'
      POSTGRES_USER:     'dbuser'
      POSTGRES_DB:       'perf_tests'
    volumes:
      - db-vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: ['postgres', '-c', 'log_statement=all']
    networks:
      - test-net

  app:
    image: docker.io/library/api-test:latest
    environment:
      API_DB_USER_PASSWORD: 'dbpass'
    ports:
      - '8080:8080'
    networks:
      - test-net

networks:
  test-net:

volumes:
  db-vol:
    external: true
